# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mural de Avisos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mural de Avisos
  pod 'Firebase/Analytics'
  pod 'Firebase/Database' 


end
